#!/bin/bash
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: MIT
### BEGIN INIT INFO
# Provides:       queuing
# Required-Start:    $syslog 
# Required-Stop:     $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: applies fq queuing to interfaces
# Description:       applies fq queuing to interfaces
### END INIT INFO

sysctl -q -w net.core.default_qdisc=fq

for interface in `ip -br l | awk '$1 !~ "lo|vir|wl" { print $1}'` ; do
        tc qdisc add dev $interface root fq 
        tc qdisc del dev $interface root 
done